name: qubismartlocks_fw
description: Qubi Smart Locks 

version: 2019.09.12

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

  http: any

  appresweb: any
  appadminweb: any
  appdartapiweb: any
  appiniciarsesionweb: any
  appsesionfbweb: any

  firebase: ^5.0.0

  quiver: '>=2.0.0 <3.0.0'


dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    path: ../../../flutter_web/packages/flutter_web
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web
  flutter_web_ui:
    path: ../../../flutter_web/packages/flutter_web_ui
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_ui

#  flutter_web_test:
#    path: ../../../flutter_web/packages/flutter_web_test
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_test

  appresweb:
    path: ../../../apppacksWeb/appresweb/
  appadminweb:
    path: ../../../apppacksWeb/appadminweb/
  appdartapiweb:
    path: ../../../apppacksWeb/appdartapiweb/
  appiniciarsesionweb:
    path: ../../../apppacksWeb/appiniciarsesionweb/
  appsesionfbweb:
    path: ../../../apppacksWeb/appsesionfbweb/

flutter:

  uses-material-design: truex

